#!/usr/bin/env php
<?php
require __DIR__ . '/../vendor/autoload.php';

use Symfony\Component\Console\Application;
use Symfony\Component\DomCrawler\Crawler;
use Symfony\Component\HttpClient\HttpClient;
use Uvinum\Command\UpdateCurrencyValuesCommand;

$client = HttpClient::create();
$crawler = new Crawler();

$application = new Application();

$application
    ->add(new UpdateCurrencyValuesCommand($client, $crawler));

$application->run();
